<a href="https://colab.research.google.com/github/govindakolli/Pytorch/blob/main/02_Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Tensor Operations**


Tensor Operations are used to manipulate multi-dimensional arrays of numbers, i.e. tensors, that represent complex data.

Here are some of the tensor operations :
1. **Creating Tensors** : The *torch.tensor()* function creates a tensor from the given data.

2. **Initialize Tensors**: Initialize tensors with various values and shapes using functions like *torch.tensor()*, *torch.zeros()*, and *torch.ones()*.

3. **Random Tensors**: Generate tensors with random values using *torch.rand()*, *torch.randn()*, and *torch.randint()*.

4. **Reshaping Tensors**: Transform tensor shapes using *view()* and *reshape()*.

5. **Concatenating Tensors**: Combine multiple tensors with *torch.cat()* and *torch.stack()*.

6. **Transpose and Permutation**: Reorder tensor dimensions using *torch.transpose()* and *torch.permute()*.

7. **Converting to/from NumPy**: Seamlessly switch between PyTorch tensors and NumPy arrays using *tensor.numpy()* and *torch.from_numpy()*.





Before we begin, let's install and import PyTorch and see some functions with examples :


In [1]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [3]:
# import torch and Other modules
import torch
import numpy as np


**1. Creating tensors**

The *torch.tensor()* function creates a tensor from the given data. It is one of the most fundamental ways to create a tensor in PyTorch. The function allows you to specify the data type* (dtype)*, device *(device)*, and other properties.


*torch.tensor(data, dtype = None, device = None)* : Creates a tensor with specified data

Examples:

In [3]:
# Creates a tensor from a list
a = torch.tensor([[1, 2],[ 3, 4.]])
print(a)
#output = tensor([[1., 2.],[3., 4.]])

tensor([[1., 2.],
        [3., 4.]])


The function automatically converts the elements to a common data type (*float32* in this case) because one of the elements (*4.*) is a float. PyTorch promotes types to ensure consistency within the tensor.

In [4]:
# 2D tensor with float data

b = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
print(b)
#output =  tensor([[1., 2.],[3., 4.]])

tensor([[1., 2.],
        [3., 4.]])


Here, the *dtype* argument explicitly sets the data type to *float32*. This is useful when you want precise control over the data type for operations like floating-point calculations or GPU compatibility.

In [6]:
# Mixing data types  ; # Uncomment and run to see error

# c = torch.tensor([[1, 2], [3, '4']])
# Throws: TypeError: expected scalar type int but found str

d = torch.tensor([[1, 2], [3, 4, 5]])
#ValueError: expected sequence of length 2 at dim 1 (got 3)


ValueError: expected sequence of length 2 at dim 1 (got 3)

The input list is not rectangular because the inner lists have different lengths ([1, 2] has length 2, while [3, 4, 5] has length 3). PyTorch requires all inner lists (or sequences) to have the same length to form a proper tensor.


Use *torch.tensor(*) when you want to initialize tensors from Python lists or arrays with specific properties like data type or device. Ensure the input is rectangular (same size in all dimensions) and contains valid data types to avoid errors.

**2. Initializing Tensors**

PyTorch provides various utility functions to initialize tensors with specific values, shapes, or patterns. Commonly used functions include *torch.zeros()*, *torch.ones()*, and others like *torch.eye()* for identity matrices or torch.rand() for random initialization.

*torch.zeros(size)*: Create a tensor of zeros.

*torch.ones(size)*: Create a tensor of ones.

Examples:

In [7]:
 # 2x3 tensor of zeros

zero_tensor = torch.zeros((2, 3))
print(zero_tensor)
 # Output: tensor([[0., 0., 0.], [0., 0., 0.]])

tensor([[0., 0., 0.],
        [0., 0., 0.]])



The *torch.zeros()* function creates a tensor of shape *(2, 3)* filled with zeros. The default data type is *float32*. This is commonly used for initializing weights or placeholders for computations.

In [8]:
# 2x3 tensor of ones with int type

one_tensor = torch.ones((2, 3), dtype=torch.int32)
print(one_tensor)
 # Output: tensor([[1, 1, 1], [1, 1, 1]], dtype=torch.int32)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


The *torch.ones()* function creates a tensor of shape *(2, 3)* filled with ones. Here, the dtype argument specifies the tensor's data type as int32. This is useful for tasks requiring integer-based computations.



In [4]:
# Uncomment and run to see error

invalid_tensor = torch.zeros(-1, 3)  # Negative size
# Throws: RuntimeError: shape should be of size greater than or equal to 0

RuntimeError: Trying to create tensor with negative dimension -1: [-1, 3]

The shape argument cannot contain negative values (e.g., -2). Tensor dimensions must be non-negative integers. Ensure the shape you specify is valid and represents a real tensor.


Functions like *torch.zeros()* and *torch.ones()* are essential for creating tensors with default values. They are useful for initializing model weights, placeholders, or constant tensors. Always verify the shape and data type to avoid errors during initialization.

**3. Random Tensors**


PyTorch provides functions to initialize tensors with random values. These functions are commonly used to create random data for model initialization, simulations, or testing purposes.

Common Random Tensor Functions :

*torch.rand(size)* : Generates random numbers uniformly distributed in the range [0, 1).

*torch.randn(size)* : Generates random numbers from a standard normal distribution (mean=0, std=1).


Examples:

In [10]:
 # Random values [0, 1)
rand_tensor = torch.rand((2, 2))
print(rand_tensor)


tensor([[0.8828, 0.0688],
        [0.6320, 0.6521]])


The *torch.rand()* function creates a tensor of shape *(2, 2)* filled with random values between 0 and 1. It is often used to generate test data or initialize weights in a model.

In [6]:
 # Normally distributed random values
randn_tensor = torch.randn((3, 2))
print(randn_tensor)

tensor([[-0.4864,  1.0187],
        [-1.0318,  0.1341],
        [ 1.9551, -1.4272]])


The *torch.randn()* function creates a tensor of shape *(3, 2)* with random values from a normal distribution *(mean 0 and standard deviation 1)*. This is useful for testing models that assume normally distributed data.

In [12]:
# Uncomment and run to see error

invalid_rand = torch.rand("3", 2)       # Non-integer size

# Throws: TypeError: expected TensorOptions dtype, but got str

TypeError: rand() received an invalid combination of arguments - got (str, int), but expected one of:
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, torch.Generator generator, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, Tensor out = None, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype = None, torch.layout layout = None, torch.device device = None, bool pin_memory = False, bool requires_grad = False)


The first argument must be an integer specifying the size of the tensor. Passing a string ("3") instead of an integer results in a *TypeError*. Ensure all arguments are valid numerical types.


Random tensor functions like *torch.rand()* and *torch.randn()* are essential for generating random data for testing, simulations, and model initialization. Always verify that the size argument is valid and consists of non-negative integers.

**4. Reshaping**

Reshaping a tensor is often required to prepare it for certain operations, like feeding it into a model or processing it efficiently. PyTorch provides functions like *view()* and reshape() to change the shape of a tensor without altering its data.

Key Difference:

*tensor.view(shape)*: Reshapes the tensor while keeping its original memory layout. The new shape must be compatible with the original tensor.

*tensor.reshape(shape)*: Similar to *view()*, but can create a copy of the tensor if needed, offering more flexibility.



Examples:

In [13]:
tensor = torch.arange(6)  # tensor([0, 1, 2, 3, 4, 5])
reshaped = tensor.view(2, 3)  # Reshapes into 2 rows and 3 columns

print(reshaped)

tensor([[0, 1, 2],
        [3, 4, 5]])


The *view()* function reshapes the 1D tensor with 6 elements into a 2D tensor with shape *(2, 3)*. The total number of elements *(6)* remains the same.

In [14]:
tensor = torch.arange(6)  # tensor([0, 1, 2, 3, 4, 5])
reshaped = tensor.reshape(3, 2)  # Reshapes into 3 rows and 2 columns

print(reshaped)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


The *reshape(*) function changes the shape of the tensor into (*3, 2)*. Unlike *view()*, it creates a new tensor if the original memory layout is incompatible with the requested shape.

In [15]:
tensor = torch.arange(6)  # tensor([0, 1, 2, 3, 4, 5])
reshaped = tensor.view(4, 2)  # Mismatched shape

RuntimeError: shape '[4, 2]' is invalid for input of size 6

The *view()* function fails because the requested shape *(4, 2)* does not match the total number of elements in the original tensor *(6)*. The total number of elements must remain constant when reshaping.




Use *view()* or *reshape()* to change the shape of a tensor as needed for operations like feeding data into a neural network. Ensure the new shape is compatible with the original number of elements to avoid errors. Use *reshape()* when you need more flexibility and don't mind a potential copy.



**5. Concatenating Tensors**

Concatenation combines two or more tensors along a specified dimension. PyTorch provides functions like *torch.cat()* and *torch.stack()* for this purpose.

Key Differences:

*torch.cat(tensors, dim)*: Concatenates tensors along an existing dimension.

*torch.stack(tensors, dim)*: Stacks tensors along a new dimension, increasing the rank of the tensor.

Examples :

In [16]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])
concatenated = torch.cat((tensor1, tensor2), dim=0)  # Concatenate along rows

print(concatenated)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


The *torch.cat()* function concatenates *tensor1* and *tensor2* along *dim=0* (rows). The resulting tensor has the shape of *(4, 2)* because the rows are combined, but the columns remain same.

In [17]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor3 = torch.tensor([[6, 7], [8, 9]])
stacked = torch.stack((tensor1, tensor3), dim= 0)  # stack along a new dimension

print(stacked)
print(stacked.shape)

tensor([[[1, 2],
         [3, 4]],

        [[6, 7],
         [8, 9]]])
torch.Size([2, 2, 2])


The *torch.stack()* function adds a new dimension (*dim=0*) to stack the tensors. The resulting tensor has the shape of (2, 2, 2), where the new dimension corresponds to the number of tensors stacked.

In [18]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor4 = torch.tensor([[5, 6, 7],[8, 9, 10]])
concat = torch.cat((tensor1, tensor4),dim = 1) #concat along columns

print(concat)

tensor([[ 1,  2,  5,  6,  7],
        [ 3,  4,  8,  9, 10]])


Here, *tensor1* and *tensor2* are concatenated along *dim=1* (columns). PyTorch allows this operation because the sizes along *dim=0* (rows) match, even though the number of columns differs. The resulting tensor has a shape of *(2, 5)* because the columns are combined.

In [19]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([5, 6])
concatenated = torch.cat((tensor1, tensor2), dim=0)  # Attempt to concatenate along rows


RuntimeError: Tensors must have same number of dimensions: got 2 and 1

The *torch.cat()* function fails here because the tensors have mismatched sizes in *dim=1* (columns). When concatenating along *dim=0* (rows), the column sizes must match, but *tensor1* has 2 columns while *tensor2* has only 1. This results in a *RuntimeError*.


* torch.cat() requires matching sizes in all dimensions except the one being concatenated.

* Ensure the dimensions align properly to avoid errors.

* Carefully analyze the dimensions of tensors to determine the appropriate concatenation behavior.

**6. Transpose and Permutation**

Reordering dimensions of a tensor is a common operation in PyTorch, especially for tasks like reshaping data or aligning tensor dimensions for matrix operations. PyTorch provides two key functions for this purpose:

*torch.transpose(input, dim0, dim1)* : Swaps two specified dimensions of the tensor.

*torch.permute(dims)* : Rearranges all dimensions of the tensor based on the specified order.


Key Differences:

transpose is used for swapping two dimensions and is commonly applied to 2D or higher-order tensors.

permute is more general and can reorder all dimensions of a tensor, making it useful for multi-dimensional tensors.

In [20]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
transposed = torch.transpose(tensor, 0, 1)  # Swaps rows and columns

print(transposed)


tensor([[1, 4],
        [2, 5],
        [3, 6]])


The *torch.transpose()* function swaps dimensions *0* (rows) and *1* (columns), effectively transposing the matrix.

In [21]:
tensor = torch.randn(2, 3, 4)  # Shape: (2, 3, 4)
permuted = tensor.permute(2, 0, 1)  # Rearranges dimensions to (4, 2, 3)

print(permuted.shape)


torch.Size([4, 2, 3])


The *permute()* function rearranges the dimensions of the tensor according to the specified order *(2, 0, 1)*. This is especially useful for aligning data formats, such as switching from channel-first to channel-last.

In [22]:
tensor = torch.tensor([1, 2, 3])  # 1D tensor
transposed = torch.transpose(tensor, 0, 1)  # Attempt to transpose


IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

The *torch.transpose()* function cannot be used on a 1D tensor because it requires at least two dimensions to swap. Ensure the tensor has enough dimensions before applying *transpose*.

In [23]:
tensor = torch.randn(2, 3, 4)  # Shape: (2, 3, 4)
permuted = tensor.permute(0, 0, 1)  # Invalid dimension order


RuntimeError: permute(): duplicate dims are not allowed.

The *permute()* function fails because the dimensions specified must be unique. Repeating dimensions (e.g., (0, 0, 1)) results in an error. Ensure each dimension is included exactly once.


* Use *transpose()* for simple dimension swaps (e.g., transposing matrices).


* Use *permute()* for more complex reordering of dimensions in higher-dimensional tensors.


* Always check the tensor's shape and ensure valid dimension indices to avoid runtime errors.

**7. Converting Tensors to/from NumPy**

PyTorch provides seamless integration with NumPy, allowing tensors to be converted to and from NumPy arrays. This is particularly useful for interoperability between PyTorch and other libraries that use NumPy.

Key Functions:

*tensor.numpy()*: Converts a PyTorch tensor to a NumPy array.

*torch.from_numpy(array)*: Converts a NumPy array to a PyTorch tensor.

**Note**: These conversions share memory, meaning changes to one will reflect in the other unless explicitly copied.

In [24]:
tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
numpy_array = tensor.numpy()

print(numpy_array)
print(type(numpy_array))

print(tensor.dtype)
print(numpy_array.dtype)

[1. 2. 3.]
<class 'numpy.ndarray'>
torch.float32
float32


The *torch.numpy()* method converts the PyTorch tensor to a NumPy array. The data type and values remain the same, but the object type changes.

In [25]:
numpy_array = np.array([4, 5, 6], dtype=np.float32)
tensor = torch.from_numpy(numpy_array)

print(tensor)
print(type(tensor))

tensor([4., 5., 6.])
<class 'torch.Tensor'>


The *torch.from_numpy()* function converts a NumPy array to a PyTorch tensor. The conversion maintains a shared memory relationship, meaning changes to one affect the other.

In [26]:
tensor = torch.tensor([1, 2, 3], device='cuda')  # Tensor on GPU
numpy_array = tensor.numpy()

#make sure to have NVIDIA GPU
#TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.


RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

The *numpy()* method works only for tensors stored on the CPU. If the tensor is on the GPU, you must first move it to the CPU using *.cpu()*.

In [27]:

numpy_array = np.array([4, 5, 6], dtype=np.int64)
numpy_array.flags.writeable = False  # Make the NumPy array read-only
tensor = torch.from_numpy(numpy_array)
tensor[0] = 10  # Attempt to modify the tensor


<ipython-input-27-a08d7b5dd078>:3: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at ../torch/csrc/utils/tensor_numpy.cpp:206.)
  tensor = torch.from_numpy(numpy_array)


The issue arises because *torch.from_numpy()* creates a tensor that shares memory with the NumPy array. When the NumPy array is read-only (non-writable), the corresponding PyTorch tensor cannot perform in-place modifications. PyTorch expects the underlying memory to be writable for tensors created from NumPy.

To fix this issue, you can either:

 * 1. Create a writable NumPy array:

In [28]:
numpy_array = np.array([4, 5, 6], dtype=np.int64)
tensor = torch.from_numpy(numpy_array)
tensor[0] = 10  # Works because the array is writable


* 2. Clone the tensor to decouple it from the NumPy array:

In [29]:
numpy_array = np.array([4, 5, 6], dtype=np.int64)
numpy_array.flags.writeable = False  # Read-only array
tensor = torch.from_numpy(numpy_array).clone()  # Clone to create a writable tensor
tensor[0] = 10  # Now works without error


**Shared Memory**: By default, PyTorch tensors and NumPy arrays share memory to enable efficient data interchange.


**Read-only Arrays**: If the NumPy array is read-only, you must either make it writable or clone the tensor to perform modifications.

Use *tensor.numpy()* to export PyTorch data for use in NumPy-based libraries.

Use *torch.from_numpy()* to load NumPy data into PyTorch workflows.

Ensure the tensor is on the CPU and the NumPy array is writable to avoid errors during conversion.

 **Conclusion**

In this notbook, we explored the most commonly used **tensor operations** in PyTorch, covering their functionality, practical examples, and common pitfalls. Here's a quick recap:

1. **Creating Tensors** : The *torch.tensor()* function creates a tensor from the given data.

2. **Initialize Tensors**: Initialize tensors with various values and shapes using functions like *torch.tensor()*, *torch.zeros()*, and *torch.ones()*.

3. **Random Tensors**: Generate tensors with random values using *torch.rand()*, *torch.randn()*, and *torch.randint()*.

4. **Reshaping Tensors**: Transform tensor shapes using *view()* and *reshape()*.

5. **Concatenating Tensors**: Combine multiple tensors with *torch.cat()* and *torch.stack()*.

6. **Transpose and Permutation**: Reorder tensor dimensions using *torch.transpose()* and *torch.permute()*.

7. **Converting to/from NumPy**: Seamlessly switch between PyTorch tensors and NumPy arrays using *tensor.numpy()* and *torch.from_numpy()*.

Each operation was demonstrated with working examples, including breaking cases to understand potential errors and how to handle them.

**Where to Go Next**

Now that you understand the basics of PyTorch tensor operations, here’s what you can do next:

1. **Deep Dive into Advanced Tensor Operations** : Explore slicing, broadcasting, and element-wise operations.

2. **Learn PyTorch's Autograd System**: Understand automatic differentiation and gradient computation.

3. **Build Models**: Start applying these operations in neural network architectures.

4. **Explore PyTorch Ecosystem**: Use libraries like torchvision for image processing or torchaudio for sound analysis.

With practice and exploration, you’ll soon be adept at handling tensors in any deep learning project!

**Reference Links**
1. Official documentation for tensor operations : https://pytorch.org/docs/stable/torch.html

2. Introduction to PyTorch Tutorials : https://pytorch.org/tutorials/



3. Deep Learning with PyTorch (Book by Eli Stevens et al.)

4. Deep Learning with PyTorch - Zero to GANs by Jovian : https://jovian.com/learn/deep-learning-with-pytorch-zero-to-gans
