<a href="https://colab.research.google.com/github/govindakolli/Pytorch/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **00. PyTorch Fundamentals**

Resource Notebook : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [ ]:
!nvidia-smi #GPU only

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors
### Creating Tensors

Pytorch tensors are created using `torch.tensor()` - https://docs.pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get the tensor back as Python int
scalar.item()

7

In [ ]:
# Vectors
vector = torch.tensor([7, 7 ])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
#vector.item()
#RuntimeError: a Tensor with 2 elements cannot be converted to Scalar

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7, 8 ],
                       [9, 10 ]])
MATRIX
# Note : matrix and tensors are denoted by capital letters in mathematics

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0], MATRIX[1] #rows

(tensor([7, 8]), tensor([ 9, 10]))

In [ ]:
MATRIX[1][0].item() # matrix[Row][Col]

9

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3 ],
                        [4, 5, 6 ]],
                         [[7, 8, 9],
                          [10, 11, 12]]])
TENSOR


tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 2, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
TENSOR[0][0]

tensor([1, 2, 3])

### Random Tensors
Why randon tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at random numbers -> update random numbers`

In [ ]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5713, 0.7921, 0.4080, 0.2478],
        [0.5390, 0.2991, 0.4067, 0.2275],
        [0.6464, 0.1729, 0.2147, 0.8011]])

In [ ]:
random_tensor.ndim

2

In [ ]:
# Create a random tensor with similar shape to an image tensor
image_tensor = torch.rand(size=(3, 224, 224)) # color channel (R, G, B),height, width
image_tensor.shape, image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones Tensor


In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating range tensors and tensors-like

In [ ]:
# Use torch.range() -> depricated
torch.range(0,10)


<ipython-input-27-1cb233606ba4>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten = torch.arange(start = 1, end = 11, step = 1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor Datatypes

**Note** : Tensor datatypes is one of the 3 big errors you'll run into in PyTorch & Deep Learning :    
1. Tensors not right datatypes
2. Tensors not right shape
3. Tensors not on the right device


In [ ]:
 # Deafault dtype is float32
 float_32_tensor = torch.tensor([3, 6, 9. ],
                                dtype = torch.float32, # what datatype is the tensor (e.g float32, float16, float64 and etc...)
                                device = None,          # what device is your tensor on
                                requires_grad=False)    # whether or not to track gradients with this tensors operations
 float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting Information from tensors


In [ ]:
# Create random tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9944, 0.8606, 0.3181, 0.0992],
        [0.8722, 0.2304, 0.5325, 0.1896],
        [0.8068, 0.3067, 0.7683, 0.8648]])

In [ ]:
# Findout details about some tensor
print(some_tensor)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.shape}")
print(f"Device of tensor is on  : {some_tensor.device}")

tensor([[0.9944, 0.8606, 0.3181, 0.0992],
        [0.8722, 0.2304, 0.5325, 0.1896],
        [0.8068, 0.3067, 0.7683, 0.8648]])
Datatype of tensor : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor is on  : cpu


### Manipulating Tensors

Tensor operations include :

* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor  = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multipy tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Subtract by 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [ ]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

## Matrix multiplication

Two main ways of performing matrix multiplication in neural networks and deep learning:

1. Element wise multiplication ( Hadamard Product)
2. Matrix multiplication (dot product)

Two rules to avoid errors:
1. Inner dimensions should match
2. Outer dimensions is the shape of resulting matrix

In [ ]:
# Element wise multiplication (Hadamard Product)
print(tensor, "*", tensor)
print(f"Equals : {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals : tensor([1, 4, 9])


In [ ]:
#Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.02 ms, sys: 178 µs, total: 1.2 ms
Wall time: 2.63 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 80 µs, sys: 0 ns, total: 80 µs
Wall time: 83.9 µs


tensor(14)

We use **Transpose** to match dimensions in matrix multiplication

In [ ]:
torch.mm(torch.rand(3,2), torch.rand(3,2).T) # mm ->matmul, .T -> Transpose

tensor([[0.2163, 0.1654, 0.4837],
        [0.7149, 0.5717, 0.9767],
        [0.4383, 0.3518, 0.5685]])

##Finding the min, max, mean, sum, etc... (tensor aggregation)

In [ ]:
#Create a tensor

x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#Find the min
torch.min(x), min(x), x.min()

(tensor(1), tensor(1), tensor(1))

In [ ]:
# Find mean  # Note : torch.mean function requires tensor of datatype float32 datatype to work
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
#Find the sum
torch.sum(x), x.sum(), sum(x)

(tensor(460), tensor(460), tensor(460))

## Finding the positional min and max

In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum  value with `argmin()` -> returns index position of min element
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum  value with `argmax()` -> returns index position of max element
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of a tensor of certain shape but keep the same memory as original tensor
* Stacking - combine, multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds all `1` dimensions to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
# Create a tensor
import torch
x = torch.arange(1,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
## Add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[ : , 0]= 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze - removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_squeeze = x_reshaped.squeeze()
x_squeeze

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
x_reshaped.squeeze().size()

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at specific dim (dimension)
print(f"Previous target tensor :{x_squeeze}")
print(f"Previous shape : {x_squeeze.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeeze.unsqueeze(dim=0)
print(f"\nNew tensor : {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")


Previous target tensorv:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])

New tensor : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim ) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0->1, 1->2, 2->0
print(f"Previous shape : {x_original.shape}")
print(f"New shape : {x_permuted.shape}") # [colour_channels, height, width]

Previous shape : torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0] = 728218
x_original[0,0,0], x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing (Selecting dayta from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
# Create a tensor
import torch
y = torch.arange(1,10).reshape(1, 3, 3)
y, y.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
y[:,:,0]

tensor([[1, 4, 7]])

In [ ]:
y[:,1,:]

tensor([[4, 5, 6]])

In [ ]:
y[0, 1, 1]

tensor(5)

In [ ]:
y[:, 1, 1]

tensor([5])

## PyTorch tensors & NumPy
NumPy is a popular scientific python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor  -> `torch.from_numpy(ndarray)`
* PyTorch tensor to NumPy Array -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)#.type(torch.float32)# Waarning : when converting from numpy -> pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [ ]:
torch.arange(1.0,8.0).dtype

torch.float32

In [ ]:
# change the value of array, what will this do to tendsor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to numpty
tensor1 = torch.ones(7)
numpy_tensor = tensor1.numpy()
tensor1, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# change the value of tensor, what will this do to numpy array?
tensor1 = tensor1 + 1
tensor1, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns :    

`start with random numbers -> tensor operations -> update random numbers to try and make them better represenations of data -> again -> again -> again...`

To reduce randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6328, 0.3724, 0.7542, 0.3348],
        [0.9006, 0.5887, 0.4037, 0.0911],
        [0.9881, 0.0456, 0.2437, 0.4957]])
tensor([[0.1158, 0.5380, 0.8889, 0.5965],
        [0.3766, 0.3455, 0.7996, 0.0330],
        [0.0381, 0.8431, 0.6305, 0.3030]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors

#set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs( Faster computations)

GPUs = faster computations on numbers

In [ ]:
 torch.cuda.is_available()

False

In [ ]:
# set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

device

'cpu'

In [ ]:
# Count number of devices
torch.cuda.device_count()

0

### Putting tensors (and models) on the GPU

In [ ]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tenor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (If available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

###  Moving tensors back to the CPU


In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy() # TypeError


array([1, 2, 3])

In [ ]:
# To fix it we move to CPU first
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])